# Median
The median is the value that separates the higher half from the lower half of a dataset when it's sorted in order. It's the middle point of your data.

- Robust to outliers: Unlike the mean, the median is not affected by extreme values
- Position-based: It only depends on the order of values, not their magnitude
- True "middle" value: Represents the 50th percentile of your data

**When to Choose Median Over Mean**
- Income data - usually right-skewed
- House prices - few expensive outliers
- Response times - occasional very slow responses
- Customer ratings - ordinal data
- Any skewed distribution where outliers would distort the mean

The median gives you a more realistic "typical" value when your data isn't perfectly symmetrical!



## Implementation
You can calculate the median using libraries like NumPy, pandas or the built-in statistics module in Python.


### 1. Using NumPy

In [1]:
import numpy as np

# Basic median calculation
data = [25, 30, 35, 40, 1000]  # Notice the outlier 1000
median_np = np.median(data)
mean_np = np.mean(data)

print(f"Data: {data}")
print(f"NumPy Median: {median_np}")  # 35.0
print(f"NumPy Mean: {mean_np:.2f}")  # 226.00
print(f"Difference: {mean_np - median_np:.2f}")  # 191.00


Data: [25, 30, 35, 40, 1000]
NumPy Median: 35.0
NumPy Mean: 226.00
Difference: 191.00


### 2. Using pandas (for DataFrames/Series)

In [2]:
import pandas as pd
import numpy as np

# Create a DataFrame with salary data
data = {
    'department': ['Engineering', 'Marketing', 'Sales', 'HR', 'Engineering'],
    'salary': [85000, 62000, 58000, 55000, 250000]  # CEO in Engineering
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Calculate median by department
median_by_dept = df.groupby('department')['salary'].median()
mean_by_dept = df.groupby('department')['salary'].mean()

print("\nMedian salary by department:")
print(median_by_dept)

print("\nMean salary by department:")
print(mean_by_dept)

# The Engineering department shows the difference clearly!

Original DataFrame:
    department  salary
0  Engineering   85000
1    Marketing   62000
2        Sales   58000
3           HR   55000
4  Engineering  250000

Median salary by department:
department
Engineering    167500.0
HR              55000.0
Marketing       62000.0
Sales           58000.0
Name: salary, dtype: float64

Mean salary by department:
department
Engineering    167500.0
HR              55000.0
Marketing       62000.0
Sales           58000.0
Name: salary, dtype: float64


### 3. Using statistics

In [3]:
import statistics

data = [25, 30, 35, 40, 1000]

# Basic median
median_stats = statistics.median(data)
print(f"Statistics Median: {median_stats}")  # 35

# For even number of elements
data_even = [25, 30, 35, 40]
median_even = statistics.median(data_even)
print(f"Median (even count): {median_even}")  # 32.5

# Low and high median functions
data_even = [1, 2, 3, 4]
low_median = statistics.median_low(data_even)   # 2
high_median = statistics.median_high(data_even) # 3
regular_median = statistics.median(data_even)   # 2.5

print(f"Low median: {low_median}")
print(f"High median: {high_median}")
print(f"Regular median: {regular_median}")

Statistics Median: 35
Median (even count): 32.5
Low median: 2
High median: 3
Regular median: 2.5


## Advanced Usage

### 1. Handling Missing Data

In [11]:
import pandas as pd
import numpy as np

# Data with missing values
data_with_nan = [1, 2, 3, np.nan, 5, 6, np.nan, 8]

# pandas automatically handles NaN values
series = pd.Series(data_with_nan)
median_with_nan = series.median()

print(f"Data with NaN: {data_with_nan}")
print(f"Median (ignoring NaN): {median_with_nan}")  # 4.0


Data with NaN: [1, 2, 3, nan, 5, 6, nan, 8]
Median (ignoring NaN): 4.0


### 2. Multi-dimensional Data

In [12]:
import numpy as np

# 2D array example
data_2d = np.array([
    [1, 2, 3, 100],    # row with outlier
    [4, 5, 6, 7],      # normal row
    [8, 9, 10, 11]     # normal row
])

# Median along different axes
median_axis0 = np.median(data_2d, axis=0)  # Column-wise median
median_axis1 = np.median(data_2d, axis=1)  # Row-wise median

print("Original 2D array:")
print(data_2d)
print(f"\nColumn-wise median: {median_axis0}")
print(f"Row-wise median: {median_axis1}")


Original 2D array:
[[  1   2   3 100]
 [  4   5   6   7]
 [  8   9  10  11]]

Column-wise median: [ 4.  5.  6. 11.]
Row-wise median: [2.5 5.5 9.5]
